export interface TableRowProps {
	/** Unique key for the row */
	rowKey?: string;
	/** Custom class name */
	className?: string;
	/** Row content (TableCell components) */
	children: React.ReactNode;
}

/**
 * TableRow component - renders a table row.
 *
 * Use with TableCell for advanced table mode.
 * Classes are generated by getRowClasses() utility.
 *
 * @param props - Component props
 * @param props.rowKey - Unique key for the row
 * @param props.className - Class name for styling (from getRowClasses)
 * @param props.children - Row content (TableCell components)
 *
 * @example
 * ```tsx
 * // Basic usage
 * <TableRow rowKey="bitcoin">
 *   <TableCell>Bitcoin</TableCell>
 *   <TableCell>$63,022</TableCell>
 * </TableRow>
 *
 * // With compound components
 * <TableBody>
 *   <TableBody.Row rowKey="1" className="bg-gray-50">
 *     <TableBody.Cell>Bitcoin</TableBody.Cell>
 *     <TableBody.Cell>$63,022</TableBody.Cell>
 *   </TableBody.Row>
 * </TableBody>
 * ```
 */
export const TableRow = ({ rowKey, className, children }: TableRowProps) => {
	return (
		<tr key={rowKey} data-row-key={rowKey} className={className}>
			{children}
		</tr>
	);
};
